blank_issues_enabled: true
contact_links:
  - name: Ask a question ðŸ’¬
    url: https://github.com/arcus-azure/arcus.eventgrid/discussions/new
    about: Ask a question or request support for using Arcus Event Grid.
